apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: rehanadi/api-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: api-env
          ports:
            - containerPort: 3000